"""Generate the pinned symbol/format discard table for all three ports.

    python3 scripts/gen_discard_tables.py --reference ../tongue-training

Step 4 of the normalizer drops general categories So, Sk, Cf, Co and Cn. Every
port asked its *runtime* which category a scalar is in — `Character.getType` on
the JVM, `Unicode.Scalar.Properties.generalCategory` in Swift, `\\p{So}` and
friends in JavaScript — and each runtime carries its own Unicode version. So the
answer changed with the host:

    same jar, same input, "abc" + four recently-assigned scalars
      JDK 17 -> "abc"                       (dropped as unassigned)
      JDK 26 -> "abc 𞀰 𐻽 𑬀 𝜥"              (kept; they are assigned now)

On Android that tracks the platform ICU, so two phones on different API levels
feed the model different features from the same text. The model was trained
against Python's Unicode 13.0.0, so that is the version pinned here: a scalar the
training data treated as unassigned must keep being discarded, however new the
runtime is.

The table is Cn-heavy by construction (unassigned space is most of the code
space), which is why it is ranges rather than a set.
"""
from __future__ import annotations

import argparse
import pathlib
import sys
import unicodedata

DISCARD = frozenset({"So", "Sk", "Cf", "Co", "Cn"})


def ranges() -> list[tuple[int, int]]:
    points = [c for c in range(0x110000) if unicodedata.category(chr(c)) in DISCARD]
    out: list[tuple[int, int]] = []
    start = previous = points[0]
    for c in points[1:]:
        if c == previous + 1:
            previous = c
            continue
        out.append((start, previous))
        start = previous = c
    out.append((start, previous))
    return out


BANNER = (
    "Scalars dropped by normalizer step 4 (Unicode general categories So, Sk, Cf,\n"
    "Co, Cn), GENERATED by scripts/gen_discard_tables.py from the Python reference.\n"
    "Do not hand-edit: regenerate instead.\n"
    "\n"
    "Pinned rather than asked of the runtime, because the runtime's answer changes\n"
    "with its Unicode version and the model was trained against Unicode {version}.\n"
    "A scalar that was unassigned then must keep being discarded on a newer host,\n"
    "or the same text yields different features on different devices."
)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--reference", type=pathlib.Path, default=pathlib.Path("../tongue-training"))
    args = ap.parse_args()
    sys.path.insert(0, str((args.reference / "src").resolve()))

    table = ranges()
    version = unicodedata.unidata_version
    banner = BANNER.format(version=version)
    root = pathlib.Path(__file__).resolve().parent.parent

    swift = "\n".join(f"    ({a:#07x}, {b:#07x})," for a, b in table)
    (root / "Sources/Tongue/DiscardTable.swift").write_text(
        "".join(f"// {line}\n" if line else "//\n" for line in banner.split("\n"))
        + "\n"
        + "// Sorted, non-overlapping; looked up by binary search.\n"
        + "let discardedRanges: [(UInt32, UInt32)] = [\n"
        + swift
        + "\n]\n",
        encoding="utf-8",
    )

    kotlin = "\n".join(f"        {a} to {b}," for a, b in table)
    (root / "packages/tongue-kotlin/src/main/kotlin/ai/desertant/tongue/DiscardTable.kt").write_text(
        "package ai.desertant.tongue\n\n"
        + "".join(f"// {line}\n" if line else "//\n" for line in banner.split("\n"))
        + "\n"
        + "// Sorted, non-overlapping; looked up by binary search.\n"
        + "internal object DiscardTable {\n"
        + "    val ranges: List<Pair<Int, Int>> = listOf(\n"
        + kotlin
        + "\n    )\n}\n",
        encoding="utf-8",
    )

    ts = "\n".join(f"  [{a}, {b}]," for a, b in table)
    (root / "packages/tongue-js/src/discard-table.ts").write_text(
        "".join(f"// {line}\n" if line else "//\n" for line in banner.split("\n"))
        + "\n"
        + "// Sorted, non-overlapping; looked up by binary search.\n"
        + "export const DISCARD_RANGES: ReadonlyArray<readonly [number, number]> = [\n"
        + ts
        + "\n];\n",
        encoding="utf-8",
    )

    print(f"wrote 3 discard tables: {len(table)} ranges, Unicode {version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
